server:
  port: 8080
  servlet:
    context-path: /assistant-service

spring:
  application.name: assistant-service
  cloud.vault:
    enabled: false
  ai:
    openai:
      api-key: dummy-openai-key
    enabled: true

whatsapp:
  api:
    url: dummy-whatsapp-url
    token: dummy-facebook-token
  webhook:
    verify:
      token: dummy-verify-token

telegram:
  enabled: true
  # todo: flag for long polling or webhook
  bot-token: dummy-telegram-token


# Disable Spring Security Autoconfig for local development without auth
autoconfigure:
  exclude:
    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
    - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
